[workspace]
resolver = "2"

members = [ "location_obfuscation","rusty-roads"]

[workspace.lints.clippy]
# all = { level = "deny", priority = 1 }
complexity = "deny"
correctness = "deny"
perf = "deny"
unwrap_used="deny"
suspicious = "warn"
todo = "warn"
