[package]
name = "location_obfuscation"
version = "0.1.0"
edition = "2024"

[dependencies]
geo-types = { version = "0.7.15", features = ["multithreading", "use-rstar_0_12"] }
rayon = "1.10.0"
rstar = "0.12.2"
rusty-roads = { path = "../rusty-roads" }

[lints]
workspace = true
