[package]
name = "sim"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.31.1", features = ["wgpu"] }
geo = { version = "0.30.0", features = ["proj"] }
nalgebra = "0.33.2"
rayon = "1.10.0"
ureq = "3.0.11"

[lints]
workspace = true
