[package]
name = "rusty-roads"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo-types = { version = "0.7.15", features = ["multithreading", "use-rstar_0_12"] }
rstar = "0.12.2"
