name: Clippy Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: rs-clippy-check
      # You may pin to the exact commit or the version.
      # uses: clechasseur/rs-clippy-check@23f6dcf86d7e4e0d98b000bba0bb81ac587c44aa
      uses: clechasseur/rs-clippy-check@v4.0.2
      # with:
        # Toolchain to use (without the `+` sign, ex. `nightly`)
        # toolchain: # optional
        # Arguments for the cargo clippy command
        # args: # optional
        # Directory where to perform cargo clippy command
        # working-directory: # optional
        # Tool to use instead of cargo ([`cross`, `cargo-hack`])
        # tool: # optional
        # Cache key used when using a non-cargo tool
        # cache-key: # optional, default is rs-clippy-check
          
